-- Run once in a Snowsight worksheet as ACCOUNTADMIN to set up the project.
-- Everything here is sized to stay comfortably inside the $400 / 30-day trial.

-- 1) Cost-safe warehouse: XSMALL, suspends after 60s idle, resumes on demand.
CREATE WAREHOUSE IF NOT EXISTS WH_XS
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Warehouse Copilot - trial-safe XSMALL warehouse';

-- 2) Database + schemas (RAW landing zone, ANALYTICS for dbt output).
CREATE DATABASE IF NOT EXISTS WAREHOUSE_COPILOT;
CREATE SCHEMA IF NOT EXISTS WAREHOUSE_COPILOT.RAW;
CREATE SCHEMA IF NOT EXISTS WAREHOUSE_COPILOT.ANALYTICS;

-- 3) Read/write role for ingestion + dbt.
CREATE ROLE IF NOT EXISTS WAREHOUSE_COPILOT_RW;
GRANT USAGE ON WAREHOUSE WH_XS TO ROLE WAREHOUSE_COPILOT_RW;
GRANT USAGE ON DATABASE WAREHOUSE_COPILOT TO ROLE WAREHOUSE_COPILOT_RW;
GRANT ALL ON SCHEMA WAREHOUSE_COPILOT.RAW TO ROLE WAREHOUSE_COPILOT_RW;
GRANT ALL ON SCHEMA WAREHOUSE_COPILOT.ANALYTICS TO ROLE WAREHOUSE_COPILOT_RW;
GRANT ALL ON FUTURE TABLES IN SCHEMA WAREHOUSE_COPILOT.RAW TO ROLE WAREHOUSE_COPILOT_RW;
GRANT ALL ON FUTURE TABLES IN SCHEMA WAREHOUSE_COPILOT.ANALYTICS TO ROLE WAREHOUSE_COPILOT_RW;

-- 4) Read-only role for the MCP server (least privilege for LLM-driven queries).
CREATE ROLE IF NOT EXISTS WAREHOUSE_COPILOT_RO;
GRANT USAGE ON WAREHOUSE WH_XS TO ROLE WAREHOUSE_COPILOT_RO;
GRANT USAGE ON DATABASE WAREHOUSE_COPILOT TO ROLE WAREHOUSE_COPILOT_RO;
GRANT USAGE ON SCHEMA WAREHOUSE_COPILOT.ANALYTICS TO ROLE WAREHOUSE_COPILOT_RO;
GRANT SELECT ON ALL TABLES IN SCHEMA WAREHOUSE_COPILOT.ANALYTICS TO ROLE WAREHOUSE_COPILOT_RO;
GRANT SELECT ON FUTURE TABLES IN SCHEMA WAREHOUSE_COPILOT.ANALYTICS TO ROLE WAREHOUSE_COPILOT_RO;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA WAREHOUSE_COPILOT.ANALYTICS TO ROLE WAREHOUSE_COPILOT_RO;

-- 5) Grant both roles to your user (replace <YOUR_USER>).
GRANT ROLE WAREHOUSE_COPILOT_RW TO USER <YOUR_USER>;
GRANT ROLE WAREHOUSE_COPILOT_RO TO USER <YOUR_USER>;

-- Tip: point the MCP server at WAREHOUSE_COPILOT_RO via SNOWFLAKE_ROLE in .env
-- so anything the LLM does is physically read-only.
